// Assemble the non-bootable boot records in `atari-src/` with spasm into
// generated (and committed) `src/*-bytes.ts` modules. Runs as part of
// `pnpm build`; spasm must be built first, which the workspace dependency
// orders. Same shape as packages/a8's build-loader.ts.
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { assemble, type Host } from "@sfotty-pie/spasm";
import prettier from "prettier";

const host: Host = {
	resolve: (specifier, fromId) => resolve(dirname(fromId), specifier),
	read: (id) => readFile(id, "utf8"),
};

interface Target {
	source: string;
	exportName: string;
	/** Exact output size, or [0, max] for "fits in". */
	size: number | [min: number, max: number];
	sizeReason: string;
	doc: string;
}

interface Output {
	file: string;
	header: string;
	targets: Target[];
}

const OUTPUTS: Output[] = [
	{
		file: "notboot-bytes.ts",
		header:
			"// Generated by build-boot.ts from atari-src/notboot.s - do not edit.",
		targets: [
			{
				source: "notboot.s",
				exportName: "NOT_BOOTABLE",
				size: [0, 128],
				sizeReason:
					"it must fit a single 128-byte sector, because that is all " +
					"DOS 1.0 reserves",
				doc: `/**
 * The boot record spift writes for a disk with a filesystem but no DOS: it
 * says so on screen and waits for RESET. Under a sector in size, so it fits
 * even DOS 1.0's single reserved boot sector; the caller pads it to the
 * variant's boot area and fills in the parameter block.
 */`,
			},
		],
	},
	{
		file: "notboot-sparta-bytes.ts",
		header:
			"// Generated by build-boot.ts from atari-src/notboot-sparta*.s - do not edit.",
		targets: [
			{
				source: "notboot-sparta.s",
				exportName: "SPARTA_NOT_BOOTABLE",
				size: 384,
				sizeReason:
					"it must be exactly the three 128-byte boot sectors a " +
					"SpartaDOS disk reserves",
				doc: `/**
 * The SpartaDOS sibling of NOT_BOOTABLE: three boot sectors whose JMP
 * signature targets $3080, where the message code sits. The formatter
 * overwrites the parameter block at $09-$2A.
 */`,
			},
			{
				source: "notboot-sparta-512.s",
				exportName: "SPARTA_NOT_BOOTABLE_512",
				size: 512,
				sizeReason:
					"it must be exactly the one full-size boot sector a " +
					"512-byte-sector SpartaDOS disk reserves",
				doc: `/**
 * The 512-byte-sector variant: one full-size boot sector, JMP $0440
 * signature, same parameter block for the formatter to fill.
 */`,
			},
		],
	},
];

for (const output of OUTPUTS) {
	const parts: string[] = [output.header];
	let total = 0;
	for (const target of output.targets) {
		const entry = resolve(import.meta.dirname, "../atari-src", target.source);
		const result = await assemble(entry, host);
		for (const diagnostic of result.diagnostics) {
			process.stderr.write(
				`${diagnostic.formatted ?? `${diagnostic.type}: ${diagnostic.message}`}\n`,
			);
		}
		if (result.diagnostics.some((d) => d.type === "error")) {
			process.exit(1);
		}
		const length = result.output.length;
		const fits =
			typeof target.size === "number"
				? length === target.size
				: length >= target.size[0] && length <= target.size[1];
		if (!fits) {
			process.stderr.write(
				`${target.source} assembled to ${length} bytes; ${target.sizeReason}\n`,
			);
			process.exit(1);
		}
		const bytes = [...result.output]
			.map((byte) => `0x${byte.toString(16).padStart(2, "0")}`)
			.join(", ");
		parts.push(
			`${target.doc}\nexport const ${target.exportName} = Uint8Array.from([${bytes}]);`,
		);
		total += length;
	}
	const outPath = join(import.meta.dirname, output.file);
	const config = await prettier.resolveConfig(outPath);
	await writeFile(
		outPath,
		await prettier.format(parts.join("\n\n") + "\n", {
			...config,
			parser: "typescript",
		}),
	);
	process.stdout.write(`Wrote src/${output.file} (${total} bytes).\n`);
}
