// Assemble the non-bootable boot record in `atari-src/` with spasm into the
// generated (and committed) `src/notboot-bytes.ts`. Runs as part of
// `pnpm build`; spasm must be built first, which the workspace dependency
// orders. Same shape as packages/a8's build-loader.ts.
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { assemble, type Host } from "@sfotty-pie/spasm";
import prettier from "prettier";

const host: Host = {
	resolve: (specifier, fromId) => resolve(dirname(fromId), specifier),
	read: (id) => readFile(id, "utf8"),
};

const entry = resolve(import.meta.dirname, "../atari-src/notboot.s");
const result = await assemble(entry, host);
for (const diagnostic of result.diagnostics) {
	process.stderr.write(
		`${diagnostic.formatted ?? `${diagnostic.type}: ${diagnostic.message}`}\n`,
	);
}
if (result.diagnostics.some((d) => d.type === "error")) {
	process.exit(1);
}
// It has to fit one 128-byte sector, since DOS 1.0 reserves only that much.
if (result.output.length > 128) {
	process.stderr.write(
		`notboot.s assembled to ${result.output.length} bytes; it must fit a ` +
			`single 128-byte sector, because that is all DOS 1.0 reserves\n`,
	);
	process.exit(1);
}

const bytes = [...result.output]
	.map((byte) => `0x${byte.toString(16).padStart(2, "0")}`)
	.join(", ");
const output = `// Generated by build-boot.ts from atari-src/notboot.s - do not edit.

/**
 * The boot record spift writes for a disk with a filesystem but no DOS: it
 * says so on screen and waits for RESET. Under a sector in size, so it fits
 * even DOS 1.0's single reserved boot sector; the caller pads it to the
 * variant's boot area and fills in the parameter block.
 */
export const NOT_BOOTABLE = Uint8Array.from([${bytes}]);
`;
const outPath = join(import.meta.dirname, "notboot-bytes.ts");
const config = await prettier.resolveConfig(outPath);
await writeFile(
	outPath,
	await prettier.format(output, { ...config, parser: "typescript" }),
);
process.stdout.write(
	`Wrote src/notboot-bytes.ts (${result.output.length} bytes).\n`,
);
