packages:
  - packages/*
  - apps/*
  - examples/*

strictPeerDependencies: false
sideEffectsCache: false
linkWorkspacePackages: true

minimumReleaseAgeExclude:
  - "@cyco130/eslint-config"

allowBuilds:
  esbuild: true
  unrs-resolver: true
