// Generated by generate-instructions.ts — do not edit by hand.
// Regenerate with `pnpm --filter @sfotty-pie/sfotty generate:instructions`.

import type { Instruction } from "./microcode.ts";

export const NMOS_INSTRUCTIONS: Instruction[] = [
	// 00 BRK imp
	{
		opcode: 0,
		mnemonic: "BRK",
		mode: "imp",
		code: [
			["r-brk", "dummy", "ar=sp", "dr=pch"],
			["w-ar--", "dr=pcl"],
			["w-ar--", "dr=pi", "if=1"],
			["w-ar--", "s=al", "ar=vector"],
			["r-ar++", "pcl=dr"],
			["r-ar", "pch=dr", "nmi-hold"],
		],
	},
	// 01 ORA inx
	{
		opcode: 1,
		mnemonic: "ORA",
		mode: "inx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x", "dr=al"],
			["r-dr++"],
			["r-dr"],
			["r-ar", "ro-ora"],
		],
	},
	// 02 CIM imp
	{
		opcode: 2,
		mnemonic: "CIM",
		altMnemonics: ["KIL", "JAM", "HLT"],
		mode: "imp",
		undocumented: true,
		code: [
			["r-pc", "ar=ffff"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=ffff"],
			["r-ar", "cc--"],
		],
	},
	// 03 SLO inx
	{
		opcode: 3,
		mnemonic: "SLO",
		mode: "inx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x", "dr=al"],
			["r-dr++"],
			["r-dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-slo"],
			["w-ar"],
		],
	},
	// 04 NOP zpg
	{
		opcode: 4,
		mnemonic: "NOP",
		altMnemonics: ["DOP", "SKB"],
		mode: "zpg",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "nop"],
		],
	},
	// 05 ORA zpg
	{
		opcode: 5,
		mnemonic: "ORA",
		mode: "zpg",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ro-ora"],
		],
	},
	// 06 ASL zpg
	{
		opcode: 6,
		mnemonic: "ASL",
		mode: "zpg",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-asl"],
			["w-ar"],
		],
	},
	// 07 SLO zpg
	{
		opcode: 7,
		mnemonic: "SLO",
		mode: "zpg",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-slo"],
			["w-ar"],
		],
	},
	// 08 PHP imp
	{
		opcode: 8,
		mnemonic: "PHP",
		mode: "imp",
		code: [
			["r-pc", "dummy", "ar=sp", "dr=p"],
			["w-ar--", "s=al"],
		],
	},
	// 09 ORA imm
	{
		opcode: 9,
		mnemonic: "ORA",
		mode: "imm",
		code: [["r-pc++", "ro-ora"]],
	},
	// 0A ASL acc
	{
		opcode: 10,
		mnemonic: "ASL",
		mode: "acc",
		code: [["r-pc", "dummy", "asla"]],
	},
	// 0B ANC imm
	{
		opcode: 11,
		mnemonic: "ANC",
		altMnemonics: ["AAC"],
		mode: "imm",
		undocumented: true,
		code: [["r-pc++", "ro-anc"]],
	},
	// 0C NOP abs
	{
		opcode: 12,
		mnemonic: "NOP",
		altMnemonics: ["TOP", "SKW"],
		mode: "abs",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar", "nop"],
		],
	},
	// 0D ORA abs
	{
		opcode: 13,
		mnemonic: "ORA",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar", "ro-ora"],
		],
	},
	// 0E ASL abs
	{
		opcode: 14,
		mnemonic: "ASL",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-asl"],
			["w-ar"],
		],
	},
	// 0F SLO abs
	{
		opcode: 15,
		mnemonic: "SLO",
		mode: "abs",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-slo"],
			["w-ar"],
		],
	},
	// 10 BPL rel
	{
		opcode: 16,
		mnemonic: "BPL",
		mode: "rel",
		code: [
			["r-pc++", "pl?"],
			["r-pc", "dummy", "pc+=dr?"],
			["r-pc", "dummy", "pch=fix"],
		],
	},
	// 11 ORA iny
	{
		opcode: 17,
		mnemonic: "ORA",
		mode: "iny",
		code: [
			["r-pc++", "ar=dr"],
			["r-dr++"],
			["r-dr", "ar+=y?"],
			["r-ar", "?", "ah++", "ro-ora"],
			["r-ar", "ro-ora"],
		],
	},
	// 12 CIM imp
	{
		opcode: 18,
		mnemonic: "CIM",
		altMnemonics: ["KIL", "JAM", "HLT"],
		mode: "imp",
		undocumented: true,
		code: [
			["r-pc", "ar=ffff"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=ffff"],
			["r-ar", "cc--"],
		],
	},
	// 13 SLO iny
	{
		opcode: 19,
		mnemonic: "SLO",
		mode: "iny",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-dr++"],
			["r-dr", "ar+=y?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-slo"],
			["w-ar"],
		],
	},
	// 14 NOP zpx
	{
		opcode: 20,
		mnemonic: "NOP",
		altMnemonics: ["DOP", "SKB"],
		mode: "zpx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar", "nop"],
		],
	},
	// 15 ORA zpx
	{
		opcode: 21,
		mnemonic: "ORA",
		mode: "zpx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar", "ro-ora"],
		],
	},
	// 16 ASL zpx
	{
		opcode: 22,
		mnemonic: "ASL",
		mode: "zpx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar"],
			["w-ar", "dummy", "mo-asl"],
			["w-ar"],
		],
	},
	// 17 SLO zpx
	{
		opcode: 23,
		mnemonic: "SLO",
		mode: "zpx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar"],
			["w-ar", "dummy", "mo-slo"],
			["w-ar"],
		],
	},
	// 18 CLC imp
	{
		opcode: 24,
		mnemonic: "CLC",
		mode: "imp",
		code: [["r-pc", "dummy", "cf=0"]],
	},
	// 19 ORA aby
	{
		opcode: 25,
		mnemonic: "ORA",
		mode: "aby",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "?", "ah++", "ro-ora"],
			["r-ar", "ro-ora"],
		],
	},
	// 1A NOP imp
	{
		opcode: 26,
		mnemonic: "NOP",
		mode: "imp",
		undocumented: true,
		code: [["r-pc", "dummy"]],
	},
	// 1B SLO aby
	{
		opcode: 27,
		mnemonic: "SLO",
		mode: "aby",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-slo"],
			["w-ar"],
		],
	},
	// 1C NOP abx
	{
		opcode: 28,
		mnemonic: "NOP",
		altMnemonics: ["TOP", "SKW"],
		mode: "abx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?", "ah++", "nop"],
			["r-ar", "nop"],
		],
	},
	// 1D ORA abx
	{
		opcode: 29,
		mnemonic: "ORA",
		mode: "abx",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?", "ah++", "ro-ora"],
			["r-ar", "ro-ora"],
		],
	},
	// 1E ASL abx
	{
		opcode: 30,
		mnemonic: "ASL",
		mode: "abx",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-asl"],
			["w-ar"],
		],
	},
	// 1F SLO abx
	{
		opcode: 31,
		mnemonic: "SLO",
		mode: "abx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-slo"],
			["w-ar"],
		],
	},
	// 20 JSR abs
	{
		opcode: 32,
		mnemonic: "JSR",
		mode: "abs",
		code: [
			["r-pc++", "ar=sp", "s=dr"],
			["r-ar", "dummy", "dr=pch"],
			["w-ar--", "dr=pcl"],
			["w-ar--"],
			["r-pc", "pcl=s", "s=al", "pch=dr"],
		],
	},
	// 21 AND inx
	{
		opcode: 33,
		mnemonic: "AND",
		mode: "inx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x", "dr=al"],
			["r-dr++"],
			["r-dr"],
			["r-ar", "ro-and"],
		],
	},
	// 22 CIM imp
	{
		opcode: 34,
		mnemonic: "CIM",
		altMnemonics: ["KIL", "JAM", "HLT"],
		mode: "imp",
		undocumented: true,
		code: [
			["r-pc", "ar=ffff"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=ffff"],
			["r-ar", "cc--"],
		],
	},
	// 23 RLA inx
	{
		opcode: 35,
		mnemonic: "RLA",
		mode: "inx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x", "dr=al"],
			["r-dr++"],
			["r-dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-rla"],
			["w-ar"],
		],
	},
	// 24 BIT zpg
	{
		opcode: 36,
		mnemonic: "BIT",
		mode: "zpg",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ro-bit"],
		],
	},
	// 25 AND zpg
	{
		opcode: 37,
		mnemonic: "AND",
		mode: "zpg",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ro-and"],
		],
	},
	// 26 ROL zpg
	{
		opcode: 38,
		mnemonic: "ROL",
		mode: "zpg",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-rol"],
			["w-ar"],
		],
	},
	// 27 RLA zpg
	{
		opcode: 39,
		mnemonic: "RLA",
		mode: "zpg",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-rla"],
			["w-ar"],
		],
	},
	// 28 PLP imp
	{
		opcode: 40,
		mnemonic: "PLP",
		mode: "imp",
		code: [
			["r-pc", "dummy", "ar=sp"],
			["r-ar++", "dummy"],
			["r-ar", "s=al", "p=dr"],
		],
	},
	// 29 AND imm
	{
		opcode: 41,
		mnemonic: "AND",
		mode: "imm",
		code: [["r-pc++", "ro-and"]],
	},
	// 2A ROL acc
	{
		opcode: 42,
		mnemonic: "ROL",
		mode: "acc",
		code: [["r-pc", "dummy", "rola"]],
	},
	// 2B ANC imm
	{
		opcode: 43,
		mnemonic: "ANC",
		altMnemonics: ["AAC"],
		mode: "imm",
		undocumented: true,
		code: [["r-pc++", "ro-anc"]],
	},
	// 2C BIT abs
	{
		opcode: 44,
		mnemonic: "BIT",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar", "ro-bit"],
		],
	},
	// 2D AND abs
	{
		opcode: 45,
		mnemonic: "AND",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar", "ro-and"],
		],
	},
	// 2E ROL abs
	{
		opcode: 46,
		mnemonic: "ROL",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-rol"],
			["w-ar"],
		],
	},
	// 2F RLA abs
	{
		opcode: 47,
		mnemonic: "RLA",
		mode: "abs",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-rla"],
			["w-ar"],
		],
	},
	// 30 BMI rel
	{
		opcode: 48,
		mnemonic: "BMI",
		mode: "rel",
		code: [
			["r-pc++", "mi?"],
			["r-pc", "dummy", "pc+=dr?"],
			["r-pc", "dummy", "pch=fix"],
		],
	},
	// 31 AND iny
	{
		opcode: 49,
		mnemonic: "AND",
		mode: "iny",
		code: [
			["r-pc++", "ar=dr"],
			["r-dr++"],
			["r-dr", "ar+=y?"],
			["r-ar", "?", "ah++", "ro-and"],
			["r-ar", "ro-and"],
		],
	},
	// 32 CIM imp
	{
		opcode: 50,
		mnemonic: "CIM",
		altMnemonics: ["KIL", "JAM", "HLT"],
		mode: "imp",
		undocumented: true,
		code: [
			["r-pc", "ar=ffff"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=ffff"],
			["r-ar", "cc--"],
		],
	},
	// 33 RLA iny
	{
		opcode: 51,
		mnemonic: "RLA",
		mode: "iny",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-dr++"],
			["r-dr", "ar+=y?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-rla"],
			["w-ar"],
		],
	},
	// 34 NOP zpx
	{
		opcode: 52,
		mnemonic: "NOP",
		altMnemonics: ["DOP", "SKB"],
		mode: "zpx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar", "nop"],
		],
	},
	// 35 AND zpx
	{
		opcode: 53,
		mnemonic: "AND",
		mode: "zpx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar", "ro-and"],
		],
	},
	// 36 ROL zpx
	{
		opcode: 54,
		mnemonic: "ROL",
		mode: "zpx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar"],
			["w-ar", "dummy", "mo-rol"],
			["w-ar"],
		],
	},
	// 37 RLA zpx
	{
		opcode: 55,
		mnemonic: "RLA",
		mode: "zpx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar"],
			["w-ar", "dummy", "mo-rla"],
			["w-ar"],
		],
	},
	// 38 SEC imp
	{
		opcode: 56,
		mnemonic: "SEC",
		mode: "imp",
		code: [["r-pc", "dummy", "cf=1"]],
	},
	// 39 AND aby
	{
		opcode: 57,
		mnemonic: "AND",
		mode: "aby",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "?", "ah++", "ro-and"],
			["r-ar", "ro-and"],
		],
	},
	// 3A NOP imp
	{
		opcode: 58,
		mnemonic: "NOP",
		mode: "imp",
		undocumented: true,
		code: [["r-pc", "dummy"]],
	},
	// 3B RLA aby
	{
		opcode: 59,
		mnemonic: "RLA",
		mode: "aby",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-rla"],
			["w-ar"],
		],
	},
	// 3C NOP abx
	{
		opcode: 60,
		mnemonic: "NOP",
		altMnemonics: ["TOP", "SKW"],
		mode: "abx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?", "ah++", "nop"],
			["r-ar", "nop"],
		],
	},
	// 3D AND abx
	{
		opcode: 61,
		mnemonic: "AND",
		mode: "abx",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?", "ah++", "ro-and"],
			["r-ar", "ro-and"],
		],
	},
	// 3E ROL abx
	{
		opcode: 62,
		mnemonic: "ROL",
		mode: "abx",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-rol"],
			["w-ar"],
		],
	},
	// 3F RLA abx
	{
		opcode: 63,
		mnemonic: "RLA",
		mode: "abx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-rla"],
			["w-ar"],
		],
	},
	// 40 RTI imp
	{
		opcode: 64,
		mnemonic: "RTI",
		mode: "imp",
		code: [
			["r-pc", "dummy", "ar=sp"],
			["r-ar++", "dummy"],
			["r-ar++", "p=dr"],
			["r-ar++", "pcl=dr"],
			["r-ar", "pch=dr", "s=al"],
		],
	},
	// 41 EOR inx
	{
		opcode: 65,
		mnemonic: "EOR",
		mode: "inx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x", "dr=al"],
			["r-dr++"],
			["r-dr"],
			["r-ar", "ro-eor"],
		],
	},
	// 42 CIM imp
	{
		opcode: 66,
		mnemonic: "CIM",
		altMnemonics: ["KIL", "JAM", "HLT"],
		mode: "imp",
		undocumented: true,
		code: [
			["r-pc", "ar=ffff"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=ffff"],
			["r-ar", "cc--"],
		],
	},
	// 43 SRE inx
	{
		opcode: 67,
		mnemonic: "SRE",
		mode: "inx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x", "dr=al"],
			["r-dr++"],
			["r-dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-sre"],
			["w-ar"],
		],
	},
	// 44 NOP zpg
	{
		opcode: 68,
		mnemonic: "NOP",
		altMnemonics: ["DOP", "SKB"],
		mode: "zpg",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "nop"],
		],
	},
	// 45 EOR zpg
	{
		opcode: 69,
		mnemonic: "EOR",
		mode: "zpg",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ro-eor"],
		],
	},
	// 46 LSR zpg
	{
		opcode: 70,
		mnemonic: "LSR",
		mode: "zpg",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-lsr"],
			["w-ar"],
		],
	},
	// 47 SRE zpg
	{
		opcode: 71,
		mnemonic: "SRE",
		mode: "zpg",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-sre"],
			["w-ar"],
		],
	},
	// 48 PHA imp
	{
		opcode: 72,
		mnemonic: "PHA",
		mode: "imp",
		code: [
			["r-pc", "dummy", "ar=sp", "dr=a"],
			["w-ar--", "s=al"],
		],
	},
	// 49 EOR imm
	{
		opcode: 73,
		mnemonic: "EOR",
		mode: "imm",
		code: [["r-pc++", "ro-eor"]],
	},
	// 4A LSR acc
	{
		opcode: 74,
		mnemonic: "LSR",
		mode: "acc",
		code: [["r-pc", "dummy", "lsra"]],
	},
	// 4B ASR imm
	{
		opcode: 75,
		mnemonic: "ASR",
		altMnemonics: ["ALR"],
		mode: "imm",
		undocumented: true,
		code: [["r-pc++", "ro-asr"]],
	},
	// 4C JMP abs
	{
		opcode: 76,
		mnemonic: "JMP",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc", "pcl=al", "pch=dr"],
		],
	},
	// 4D EOR abs
	{
		opcode: 77,
		mnemonic: "EOR",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar", "ro-eor"],
		],
	},
	// 4E LSR abs
	{
		opcode: 78,
		mnemonic: "LSR",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-lsr"],
			["w-ar"],
		],
	},
	// 4F SRE abs
	{
		opcode: 79,
		mnemonic: "SRE",
		mode: "abs",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-sre"],
			["w-ar"],
		],
	},
	// 50 BVC rel
	{
		opcode: 80,
		mnemonic: "BVC",
		mode: "rel",
		code: [
			["r-pc++", "vc?"],
			["r-pc", "dummy", "pc+=dr?"],
			["r-pc", "dummy", "pch=fix"],
		],
	},
	// 51 EOR iny
	{
		opcode: 81,
		mnemonic: "EOR",
		mode: "iny",
		code: [
			["r-pc++", "ar=dr"],
			["r-dr++"],
			["r-dr", "ar+=y?"],
			["r-ar", "?", "ah++", "ro-eor"],
			["r-ar", "ro-eor"],
		],
	},
	// 52 CIM imp
	{
		opcode: 82,
		mnemonic: "CIM",
		altMnemonics: ["KIL", "JAM", "HLT"],
		mode: "imp",
		undocumented: true,
		code: [
			["r-pc", "ar=ffff"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=ffff"],
			["r-ar", "cc--"],
		],
	},
	// 53 SRE iny
	{
		opcode: 83,
		mnemonic: "SRE",
		mode: "iny",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-dr++"],
			["r-dr", "ar+=y?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-sre"],
			["w-ar"],
		],
	},
	// 54 NOP zpx
	{
		opcode: 84,
		mnemonic: "NOP",
		altMnemonics: ["DOP", "SKB"],
		mode: "zpx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar", "nop"],
		],
	},
	// 55 EOR zpx
	{
		opcode: 85,
		mnemonic: "EOR",
		mode: "zpx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar", "ro-eor"],
		],
	},
	// 56 LSR zpx
	{
		opcode: 86,
		mnemonic: "LSR",
		mode: "zpx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar"],
			["w-ar", "dummy", "mo-lsr"],
			["w-ar"],
		],
	},
	// 57 SRE zpx
	{
		opcode: 87,
		mnemonic: "SRE",
		mode: "zpx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar"],
			["w-ar", "dummy", "mo-sre"],
			["w-ar"],
		],
	},
	// 58 CLI imp
	{
		opcode: 88,
		mnemonic: "CLI",
		mode: "imp",
		code: [["r-pc", "dummy", "if=0"]],
	},
	// 59 EOR aby
	{
		opcode: 89,
		mnemonic: "EOR",
		mode: "aby",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "?", "ah++", "ro-eor"],
			["r-ar", "ro-eor"],
		],
	},
	// 5A NOP imp
	{
		opcode: 90,
		mnemonic: "NOP",
		mode: "imp",
		undocumented: true,
		code: [["r-pc", "dummy"]],
	},
	// 5B SRE aby
	{
		opcode: 91,
		mnemonic: "SRE",
		mode: "aby",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-sre"],
			["w-ar"],
		],
	},
	// 5C NOP abx
	{
		opcode: 92,
		mnemonic: "NOP",
		altMnemonics: ["TOP", "SKW"],
		mode: "abx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?", "ah++", "nop"],
			["r-ar", "nop"],
		],
	},
	// 5D EOR abx
	{
		opcode: 93,
		mnemonic: "EOR",
		mode: "abx",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?", "ah++", "ro-eor"],
			["r-ar", "ro-eor"],
		],
	},
	// 5E LSR abx
	{
		opcode: 94,
		mnemonic: "LSR",
		mode: "abx",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-lsr"],
			["w-ar"],
		],
	},
	// 5F SRE abx
	{
		opcode: 95,
		mnemonic: "SRE",
		mode: "abx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-sre"],
			["w-ar"],
		],
	},
	// 60 RTS imp
	{
		opcode: 96,
		mnemonic: "RTS",
		mode: "imp",
		code: [
			["r-pc", "dummy", "ar=sp"],
			["r-ar++", "dummy"],
			["r-ar++", "pcl=dr"],
			["r-ar", "pch=dr", "s=al"],
			["r-pc++", "dummy"],
		],
	},
	// 61 ADC inx
	{
		opcode: 97,
		mnemonic: "ADC",
		mode: "inx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x", "dr=al"],
			["r-dr++"],
			["r-dr"],
			["r-ar", "ro-adc"],
		],
	},
	// 62 CIM imp
	{
		opcode: 98,
		mnemonic: "CIM",
		altMnemonics: ["KIL", "JAM", "HLT"],
		mode: "imp",
		undocumented: true,
		code: [
			["r-pc", "ar=ffff"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=ffff"],
			["r-ar", "cc--"],
		],
	},
	// 63 RRA inx
	{
		opcode: 99,
		mnemonic: "RRA",
		mode: "inx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x", "dr=al"],
			["r-dr++"],
			["r-dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-rra"],
			["w-ar"],
		],
	},
	// 64 NOP zpg
	{
		opcode: 100,
		mnemonic: "NOP",
		altMnemonics: ["DOP", "SKB"],
		mode: "zpg",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "nop"],
		],
	},
	// 65 ADC zpg
	{
		opcode: 101,
		mnemonic: "ADC",
		mode: "zpg",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ro-adc"],
		],
	},
	// 66 ROR zpg
	{
		opcode: 102,
		mnemonic: "ROR",
		mode: "zpg",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-ror"],
			["w-ar"],
		],
	},
	// 67 RRA zpg
	{
		opcode: 103,
		mnemonic: "RRA",
		mode: "zpg",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-rra"],
			["w-ar"],
		],
	},
	// 68 PLA imp
	{
		opcode: 104,
		mnemonic: "PLA",
		mode: "imp",
		code: [
			["r-pc", "dummy", "ar=sp"],
			["r-ar++", "dummy"],
			["r-ar", "s=al", "a=dr"],
		],
	},
	// 69 ADC imm
	{
		opcode: 105,
		mnemonic: "ADC",
		mode: "imm",
		code: [["r-pc++", "ro-adc"]],
	},
	// 6A ROR acc
	{
		opcode: 106,
		mnemonic: "ROR",
		mode: "acc",
		code: [["r-pc", "dummy", "rora"]],
	},
	// 6B ARR imm
	{
		opcode: 107,
		mnemonic: "ARR",
		mode: "imm",
		undocumented: true,
		code: [["r-pc++", "ro-arr"]],
	},
	// 6C JMP ind
	{
		opcode: 108,
		mnemonic: "JMP",
		mode: "ind",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar++", "pcl=dr"],
			["r-ar", "pch=dr"],
		],
	},
	// 6D ADC abs
	{
		opcode: 109,
		mnemonic: "ADC",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar", "ro-adc"],
		],
	},
	// 6E ROR abs
	{
		opcode: 110,
		mnemonic: "ROR",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-ror"],
			["w-ar"],
		],
	},
	// 6F RRA abs
	{
		opcode: 111,
		mnemonic: "RRA",
		mode: "abs",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-rra"],
			["w-ar"],
		],
	},
	// 70 BVS rel
	{
		opcode: 112,
		mnemonic: "BVS",
		mode: "rel",
		code: [
			["r-pc++", "vs?"],
			["r-pc", "dummy", "pc+=dr?"],
			["r-pc", "dummy", "pch=fix"],
		],
	},
	// 71 ADC iny
	{
		opcode: 113,
		mnemonic: "ADC",
		mode: "iny",
		code: [
			["r-pc++", "ar=dr"],
			["r-dr++"],
			["r-dr", "ar+=y?"],
			["r-ar", "?", "ah++", "ro-adc"],
			["r-ar", "ro-adc"],
		],
	},
	// 72 CIM imp
	{
		opcode: 114,
		mnemonic: "CIM",
		altMnemonics: ["KIL", "JAM", "HLT"],
		mode: "imp",
		undocumented: true,
		code: [
			["r-pc", "ar=ffff"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=ffff"],
			["r-ar", "cc--"],
		],
	},
	// 73 RRA iny
	{
		opcode: 115,
		mnemonic: "RRA",
		mode: "iny",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-dr++"],
			["r-dr", "ar+=y?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-rra"],
			["w-ar"],
		],
	},
	// 74 NOP zpx
	{
		opcode: 116,
		mnemonic: "NOP",
		altMnemonics: ["DOP", "SKB"],
		mode: "zpx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar", "nop"],
		],
	},
	// 75 ADC zpx
	{
		opcode: 117,
		mnemonic: "ADC",
		mode: "zpx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar", "ro-adc"],
		],
	},
	// 76 ROR zpx
	{
		opcode: 118,
		mnemonic: "ROR",
		mode: "zpx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar"],
			["w-ar", "dummy", "mo-ror"],
			["w-ar"],
		],
	},
	// 77 RRA zpx
	{
		opcode: 119,
		mnemonic: "RRA",
		mode: "zpx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar"],
			["w-ar", "dummy", "mo-rra"],
			["w-ar"],
		],
	},
	// 78 SEI imp
	{
		opcode: 120,
		mnemonic: "SEI",
		mode: "imp",
		code: [["r-pc", "dummy", "if=1"]],
	},
	// 79 ADC aby
	{
		opcode: 121,
		mnemonic: "ADC",
		mode: "aby",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "?", "ah++", "ro-adc"],
			["r-ar", "ro-adc"],
		],
	},
	// 7A NOP imp
	{
		opcode: 122,
		mnemonic: "NOP",
		mode: "imp",
		undocumented: true,
		code: [["r-pc", "dummy"]],
	},
	// 7B RRA aby
	{
		opcode: 123,
		mnemonic: "RRA",
		mode: "aby",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-rra"],
			["w-ar"],
		],
	},
	// 7C NOP abx
	{
		opcode: 124,
		mnemonic: "NOP",
		altMnemonics: ["TOP", "SKW"],
		mode: "abx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?", "ah++", "nop"],
			["r-ar", "nop"],
		],
	},
	// 7D ADC abx
	{
		opcode: 125,
		mnemonic: "ADC",
		mode: "abx",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?", "ah++", "ro-adc"],
			["r-ar", "ro-adc"],
		],
	},
	// 7E ROR abx
	{
		opcode: 126,
		mnemonic: "ROR",
		mode: "abx",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-ror"],
			["w-ar"],
		],
	},
	// 7F RRA abx
	{
		opcode: 127,
		mnemonic: "RRA",
		mode: "abx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-rra"],
			["w-ar"],
		],
	},
	// 80 NOP imm
	{
		opcode: 128,
		mnemonic: "NOP",
		altMnemonics: ["DOP", "SKB"],
		mode: "imm",
		undocumented: true,
		code: [["r-pc++", "nop"]],
	},
	// 81 STA inx
	{
		opcode: 129,
		mnemonic: "STA",
		mode: "inx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x", "dr=al"],
			["r-dr++"],
			["r-dr", "sta"],
			["w-ar"],
		],
	},
	// 82 NOP imm
	{
		opcode: 130,
		mnemonic: "NOP",
		altMnemonics: ["DOP", "SKB"],
		mode: "imm",
		undocumented: true,
		code: [["r-pc++", "nop"]],
	},
	// 83 SAX inx
	{
		opcode: 131,
		mnemonic: "SAX",
		mode: "inx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x", "dr=al"],
			["r-dr++"],
			["r-dr", "sax"],
			["w-ar"],
		],
	},
	// 84 STY zpg
	{
		opcode: 132,
		mnemonic: "STY",
		mode: "zpg",
		code: [["r-pc++", "ar=dr", "sty"], ["w-ar"]],
	},
	// 85 STA zpg
	{
		opcode: 133,
		mnemonic: "STA",
		mode: "zpg",
		code: [["r-pc++", "ar=dr", "sta"], ["w-ar"]],
	},
	// 86 STX zpg
	{
		opcode: 134,
		mnemonic: "STX",
		mode: "zpg",
		code: [["r-pc++", "ar=dr", "stx"], ["w-ar"]],
	},
	// 87 SAX zpg
	{
		opcode: 135,
		mnemonic: "SAX",
		mode: "zpg",
		undocumented: true,
		code: [["r-pc++", "ar=dr", "sax"], ["w-ar"]],
	},
	// 88 DEY imp
	{
		opcode: 136,
		mnemonic: "DEY",
		mode: "imp",
		code: [["r-pc", "dummy", "y--"]],
	},
	// 89 NOP imm
	{
		opcode: 137,
		mnemonic: "NOP",
		altMnemonics: ["DOP", "SKB"],
		mode: "imm",
		undocumented: true,
		code: [["r-pc++", "nop"]],
	},
	// 8A TXA imp
	{
		opcode: 138,
		mnemonic: "TXA",
		mode: "imp",
		code: [["r-pc", "dummy", "a=x"]],
	},
	// 8B ANE imm
	{
		opcode: 139,
		mnemonic: "ANE",
		mode: "imm",
		undocumented: true,
		code: [["r-pc++", "ro-ane"]],
	},
	// 8C STY abs
	{
		opcode: 140,
		mnemonic: "STY",
		mode: "abs",
		code: [["r-pc++", "ar=dr"], ["r-pc++", "ah=dr", "sty"], ["w-ar"]],
	},
	// 8D STA abs
	{
		opcode: 141,
		mnemonic: "STA",
		mode: "abs",
		code: [["r-pc++", "ar=dr"], ["r-pc++", "ah=dr", "sta"], ["w-ar"]],
	},
	// 8E STX abs
	{
		opcode: 142,
		mnemonic: "STX",
		mode: "abs",
		code: [["r-pc++", "ar=dr"], ["r-pc++", "ah=dr", "stx"], ["w-ar"]],
	},
	// 8F SAX abs
	{
		opcode: 143,
		mnemonic: "SAX",
		mode: "abs",
		undocumented: true,
		code: [["r-pc++", "ar=dr"], ["r-pc++", "ah=dr", "sax"], ["w-ar"]],
	},
	// 90 BCC rel
	{
		opcode: 144,
		mnemonic: "BCC",
		mode: "rel",
		code: [
			["r-pc++", "cc?"],
			["r-pc", "dummy", "pc+=dr?"],
			["r-pc", "dummy", "pch=fix"],
		],
	},
	// 91 STA iny
	{
		opcode: 145,
		mnemonic: "STA",
		mode: "iny",
		code: [
			["r-pc++", "ar=dr"],
			["r-dr++"],
			["r-dr", "ar+=y?"],
			["r-ar", "dummy", "?ah++", "sta"],
			["w-ar"],
		],
	},
	// 92 CIM imp
	{
		opcode: 146,
		mnemonic: "CIM",
		altMnemonics: ["KIL", "JAM", "HLT"],
		mode: "imp",
		undocumented: true,
		code: [
			["r-pc", "ar=ffff"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=ffff"],
			["r-ar", "cc--"],
		],
	},
	// 93 SHA iny
	{
		opcode: 147,
		mnemonic: "SHA",
		mode: "iny",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-dr++"],
			["r-dr", "ar+=y?"],
			["r-ar", "dummy", "?ah++", "sha"],
			["w-ar"],
		],
	},
	// 94 STY zpx
	{
		opcode: 148,
		mnemonic: "STY",
		mode: "zpx",
		code: [["r-pc++", "ar=dr"], ["r-ar", "ar+=x", "sty"], ["w-ar"]],
	},
	// 95 STA zpx
	{
		opcode: 149,
		mnemonic: "STA",
		mode: "zpx",
		code: [["r-pc++", "ar=dr"], ["r-ar", "ar+=x", "sta"], ["w-ar"]],
	},
	// 96 STX zpy
	{
		opcode: 150,
		mnemonic: "STX",
		mode: "zpy",
		code: [["r-pc++", "ar=dr"], ["r-ar", "ar+=y", "stx"], ["w-ar"]],
	},
	// 97 SAX zpy
	{
		opcode: 151,
		mnemonic: "SAX",
		mode: "zpy",
		undocumented: true,
		code: [["r-pc++", "ar=dr"], ["r-ar", "ar+=y", "sax"], ["w-ar"]],
	},
	// 98 TYA imp
	{
		opcode: 152,
		mnemonic: "TYA",
		mode: "imp",
		code: [["r-pc", "dummy", "a=y"]],
	},
	// 99 STA aby
	{
		opcode: 153,
		mnemonic: "STA",
		mode: "aby",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "dummy", "?ah++", "sta"],
			["w-ar"],
		],
	},
	// 9A TXS imp
	{
		opcode: 154,
		mnemonic: "TXS",
		mode: "imp",
		code: [["r-pc", "dummy", "s=x"]],
	},
	// 9B SHS aby
	{
		opcode: 155,
		mnemonic: "SHS",
		mode: "aby",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "dummy", "?ah++", "shs"],
			["w-ar"],
		],
	},
	// 9C SHY abx
	{
		opcode: 156,
		mnemonic: "SHY",
		mode: "abx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "dummy", "?ah++", "shy"],
			["w-ar"],
		],
	},
	// 9D STA abx
	{
		opcode: 157,
		mnemonic: "STA",
		mode: "abx",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "dummy", "?ah++", "sta"],
			["w-ar"],
		],
	},
	// 9E SHX aby
	{
		opcode: 158,
		mnemonic: "SHX",
		mode: "aby",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "dummy", "?ah++", "shx"],
			["w-ar"],
		],
	},
	// 9F SHA aby
	{
		opcode: 159,
		mnemonic: "SHA",
		mode: "aby",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "dummy", "?ah++", "sha"],
			["w-ar"],
		],
	},
	// A0 LDY imm
	{
		opcode: 160,
		mnemonic: "LDY",
		mode: "imm",
		code: [["r-pc++", "y=dr"]],
	},
	// A1 LDA inx
	{
		opcode: 161,
		mnemonic: "LDA",
		mode: "inx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x", "dr=al"],
			["r-dr++"],
			["r-dr"],
			["r-ar", "a=dr"],
		],
	},
	// A2 LDX imm
	{
		opcode: 162,
		mnemonic: "LDX",
		mode: "imm",
		code: [["r-pc++", "x=dr"]],
	},
	// A3 LAX inx
	{
		opcode: 163,
		mnemonic: "LAX",
		mode: "inx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x", "dr=al"],
			["r-dr++"],
			["r-dr"],
			["r-ar", "ro-lax"],
		],
	},
	// A4 LDY zpg
	{
		opcode: 164,
		mnemonic: "LDY",
		mode: "zpg",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "y=dr"],
		],
	},
	// A5 LDA zpg
	{
		opcode: 165,
		mnemonic: "LDA",
		mode: "zpg",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "a=dr"],
		],
	},
	// A6 LDX zpg
	{
		opcode: 166,
		mnemonic: "LDX",
		mode: "zpg",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "x=dr"],
		],
	},
	// A7 LAX zpg
	{
		opcode: 167,
		mnemonic: "LAX",
		mode: "zpg",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ro-lax"],
		],
	},
	// A8 TAY imp
	{
		opcode: 168,
		mnemonic: "TAY",
		mode: "imp",
		code: [["r-pc", "dummy", "y=a"]],
	},
	// A9 LDA imm
	{
		opcode: 169,
		mnemonic: "LDA",
		mode: "imm",
		code: [["r-pc++", "a=dr"]],
	},
	// AA TAX imp
	{
		opcode: 170,
		mnemonic: "TAX",
		mode: "imp",
		code: [["r-pc", "dummy", "x=a"]],
	},
	// AB LXA imm
	{
		opcode: 171,
		mnemonic: "LXA",
		altMnemonics: ["ANX", "ATX", "OAL"],
		mode: "imm",
		undocumented: true,
		code: [["r-pc++", "ro-lxa"]],
	},
	// AC LDY abs
	{
		opcode: 172,
		mnemonic: "LDY",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar", "y=dr"],
		],
	},
	// AD LDA abs
	{
		opcode: 173,
		mnemonic: "LDA",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar", "a=dr"],
		],
	},
	// AE LDX abs
	{
		opcode: 174,
		mnemonic: "LDX",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar", "x=dr"],
		],
	},
	// AF LAX abs
	{
		opcode: 175,
		mnemonic: "LAX",
		mode: "abs",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar", "ro-lax"],
		],
	},
	// B0 BCS rel
	{
		opcode: 176,
		mnemonic: "BCS",
		mode: "rel",
		code: [
			["r-pc++", "cs?"],
			["r-pc", "dummy", "pc+=dr?"],
			["r-pc", "dummy", "pch=fix"],
		],
	},
	// B1 LDA iny
	{
		opcode: 177,
		mnemonic: "LDA",
		mode: "iny",
		code: [
			["r-pc++", "ar=dr"],
			["r-dr++"],
			["r-dr", "ar+=y?"],
			["r-ar", "?", "ah++", "a=dr"],
			["r-ar", "a=dr"],
		],
	},
	// B2 CIM imp
	{
		opcode: 178,
		mnemonic: "CIM",
		altMnemonics: ["KIL", "JAM", "HLT"],
		mode: "imp",
		undocumented: true,
		code: [
			["r-pc", "ar=ffff"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=ffff"],
			["r-ar", "cc--"],
		],
	},
	// B3 LAX iny
	{
		opcode: 179,
		mnemonic: "LAX",
		mode: "iny",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-dr++"],
			["r-dr", "ar+=y?"],
			["r-ar", "?", "ah++", "ro-lax"],
			["r-ar", "ro-lax"],
		],
	},
	// B4 LDY zpx
	{
		opcode: 180,
		mnemonic: "LDY",
		mode: "zpx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar", "y=dr"],
		],
	},
	// B5 LDA zpx
	{
		opcode: 181,
		mnemonic: "LDA",
		mode: "zpx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar", "a=dr"],
		],
	},
	// B6 LDX zpy
	{
		opcode: 182,
		mnemonic: "LDX",
		mode: "zpy",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=y"],
			["r-ar", "x=dr"],
		],
	},
	// B7 LAX zpy
	{
		opcode: 183,
		mnemonic: "LAX",
		mode: "zpy",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=y"],
			["r-ar", "ro-lax"],
		],
	},
	// B8 CLV imp
	{
		opcode: 184,
		mnemonic: "CLV",
		mode: "imp",
		code: [["r-pc", "dummy", "of=0"]],
	},
	// B9 LDA aby
	{
		opcode: 185,
		mnemonic: "LDA",
		mode: "aby",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "?", "ah++", "a=dr"],
			["r-ar", "a=dr"],
		],
	},
	// BA TSX imp
	{
		opcode: 186,
		mnemonic: "TSX",
		mode: "imp",
		code: [["r-pc", "dummy", "x=s"]],
	},
	// BB LAS aby
	{
		opcode: 187,
		mnemonic: "LAS",
		altMnemonics: ["LAR", "LAE"],
		mode: "aby",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "?", "ah++", "ro-las"],
			["r-ar", "ro-las"],
		],
	},
	// BC LDY abx
	{
		opcode: 188,
		mnemonic: "LDY",
		mode: "abx",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?", "ah++", "y=dr"],
			["r-ar", "y=dr"],
		],
	},
	// BD LDA abx
	{
		opcode: 189,
		mnemonic: "LDA",
		mode: "abx",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?", "ah++", "a=dr"],
			["r-ar", "a=dr"],
		],
	},
	// BE LDX aby
	{
		opcode: 190,
		mnemonic: "LDX",
		mode: "aby",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "?", "ah++", "x=dr"],
			["r-ar", "x=dr"],
		],
	},
	// BF LAX aby
	{
		opcode: 191,
		mnemonic: "LAX",
		mode: "aby",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "?", "ah++", "ro-lax"],
			["r-ar", "ro-lax"],
		],
	},
	// C0 CPY imm
	{
		opcode: 192,
		mnemonic: "CPY",
		mode: "imm",
		code: [["r-pc++", "ro-cpy"]],
	},
	// C1 CMP inx
	{
		opcode: 193,
		mnemonic: "CMP",
		mode: "inx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x", "dr=al"],
			["r-dr++"],
			["r-dr"],
			["r-ar", "ro-cmp"],
		],
	},
	// C2 NOP imm
	{
		opcode: 194,
		mnemonic: "NOP",
		altMnemonics: ["DOP", "SKB"],
		mode: "imm",
		undocumented: true,
		code: [["r-pc++", "nop"]],
	},
	// C3 DCP inx
	{
		opcode: 195,
		mnemonic: "DCP",
		altMnemonics: ["DCM"],
		mode: "inx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x", "dr=al"],
			["r-dr++"],
			["r-dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-dcp"],
			["w-ar"],
		],
	},
	// C4 CPY zpg
	{
		opcode: 196,
		mnemonic: "CPY",
		mode: "zpg",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ro-cpy"],
		],
	},
	// C5 CMP zpg
	{
		opcode: 197,
		mnemonic: "CMP",
		mode: "zpg",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ro-cmp"],
		],
	},
	// C6 DEC zpg
	{
		opcode: 198,
		mnemonic: "DEC",
		mode: "zpg",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-dec"],
			["w-ar"],
		],
	},
	// C7 DCP zpg
	{
		opcode: 199,
		mnemonic: "DCP",
		altMnemonics: ["DCM"],
		mode: "zpg",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-dcp"],
			["w-ar"],
		],
	},
	// C8 INY imp
	{
		opcode: 200,
		mnemonic: "INY",
		mode: "imp",
		code: [["r-pc", "dummy", "y++"]],
	},
	// C9 CMP imm
	{
		opcode: 201,
		mnemonic: "CMP",
		mode: "imm",
		code: [["r-pc++", "ro-cmp"]],
	},
	// CA DEX imp
	{
		opcode: 202,
		mnemonic: "DEX",
		mode: "imp",
		code: [["r-pc", "dummy", "x--"]],
	},
	// CB SBX imm
	{
		opcode: 203,
		mnemonic: "SBX",
		mode: "imm",
		undocumented: true,
		code: [["r-pc++", "ro-sbx"]],
	},
	// CC CPY abs
	{
		opcode: 204,
		mnemonic: "CPY",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar", "ro-cpy"],
		],
	},
	// CD CMP abs
	{
		opcode: 205,
		mnemonic: "CMP",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar", "ro-cmp"],
		],
	},
	// CE DEC abs
	{
		opcode: 206,
		mnemonic: "DEC",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-dec"],
			["w-ar"],
		],
	},
	// CF DCP abs
	{
		opcode: 207,
		mnemonic: "DCP",
		altMnemonics: ["DCM"],
		mode: "abs",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-dcp"],
			["w-ar"],
		],
	},
	// D0 BNE rel
	{
		opcode: 208,
		mnemonic: "BNE",
		mode: "rel",
		code: [
			["r-pc++", "ne?"],
			["r-pc", "dummy", "pc+=dr?"],
			["r-pc", "dummy", "pch=fix"],
		],
	},
	// D1 CMP iny
	{
		opcode: 209,
		mnemonic: "CMP",
		mode: "iny",
		code: [
			["r-pc++", "ar=dr"],
			["r-dr++"],
			["r-dr", "ar+=y?"],
			["r-ar", "?", "ah++", "ro-cmp"],
			["r-ar", "ro-cmp"],
		],
	},
	// D2 CIM imp
	{
		opcode: 210,
		mnemonic: "CIM",
		altMnemonics: ["KIL", "JAM", "HLT"],
		mode: "imp",
		undocumented: true,
		code: [
			["r-pc", "ar=ffff"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=ffff"],
			["r-ar", "cc--"],
		],
	},
	// D3 DCP iny
	{
		opcode: 211,
		mnemonic: "DCP",
		altMnemonics: ["DCM"],
		mode: "iny",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-dr++"],
			["r-dr", "ar+=y?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-dcp"],
			["w-ar"],
		],
	},
	// D4 NOP zpx
	{
		opcode: 212,
		mnemonic: "NOP",
		altMnemonics: ["DOP", "SKB"],
		mode: "zpx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar", "nop"],
		],
	},
	// D5 CMP zpx
	{
		opcode: 213,
		mnemonic: "CMP",
		mode: "zpx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar", "ro-cmp"],
		],
	},
	// D6 DEC zpx
	{
		opcode: 214,
		mnemonic: "DEC",
		mode: "zpx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar"],
			["w-ar", "dummy", "mo-dec"],
			["w-ar"],
		],
	},
	// D7 DCP zpx
	{
		opcode: 215,
		mnemonic: "DCP",
		altMnemonics: ["DCM"],
		mode: "zpx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar"],
			["w-ar", "dummy", "mo-dcp"],
			["w-ar"],
		],
	},
	// D8 CLD imp
	{
		opcode: 216,
		mnemonic: "CLD",
		mode: "imp",
		code: [["r-pc", "dummy", "df=0"]],
	},
	// D9 CMP aby
	{
		opcode: 217,
		mnemonic: "CMP",
		mode: "aby",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "?", "ah++", "ro-cmp"],
			["r-ar", "ro-cmp"],
		],
	},
	// DA NOP imp
	{
		opcode: 218,
		mnemonic: "NOP",
		mode: "imp",
		undocumented: true,
		code: [["r-pc", "dummy"]],
	},
	// DB DCP aby
	{
		opcode: 219,
		mnemonic: "DCP",
		altMnemonics: ["DCM"],
		mode: "aby",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-dcp"],
			["w-ar"],
		],
	},
	// DC NOP abx
	{
		opcode: 220,
		mnemonic: "NOP",
		altMnemonics: ["TOP", "SKW"],
		mode: "abx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?", "ah++", "nop"],
			["r-ar", "nop"],
		],
	},
	// DD CMP abx
	{
		opcode: 221,
		mnemonic: "CMP",
		mode: "abx",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?", "ah++", "ro-cmp"],
			["r-ar", "ro-cmp"],
		],
	},
	// DE DEC abx
	{
		opcode: 222,
		mnemonic: "DEC",
		mode: "abx",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-dec"],
			["w-ar"],
		],
	},
	// DF DCP abx
	{
		opcode: 223,
		mnemonic: "DCP",
		altMnemonics: ["DCM"],
		mode: "abx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-dcp"],
			["w-ar"],
		],
	},
	// E0 CPX imm
	{
		opcode: 224,
		mnemonic: "CPX",
		mode: "imm",
		code: [["r-pc++", "ro-cpx"]],
	},
	// E1 SBC inx
	{
		opcode: 225,
		mnemonic: "SBC",
		mode: "inx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x", "dr=al"],
			["r-dr++"],
			["r-dr"],
			["r-ar", "ro-sbc"],
		],
	},
	// E2 NOP imm
	{
		opcode: 226,
		mnemonic: "NOP",
		altMnemonics: ["DOP", "SKB"],
		mode: "imm",
		undocumented: true,
		code: [["r-pc++", "nop"]],
	},
	// E3 ISB inx
	{
		opcode: 227,
		mnemonic: "ISB",
		altMnemonics: ["INS", "ISC"],
		mode: "inx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x", "dr=al"],
			["r-dr++"],
			["r-dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-isb"],
			["w-ar"],
		],
	},
	// E4 CPX zpg
	{
		opcode: 228,
		mnemonic: "CPX",
		mode: "zpg",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ro-cpx"],
		],
	},
	// E5 SBC zpg
	{
		opcode: 229,
		mnemonic: "SBC",
		mode: "zpg",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ro-sbc"],
		],
	},
	// E6 INC zpg
	{
		opcode: 230,
		mnemonic: "INC",
		mode: "zpg",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-inc"],
			["w-ar"],
		],
	},
	// E7 ISB zpg
	{
		opcode: 231,
		mnemonic: "ISB",
		altMnemonics: ["INS", "ISC"],
		mode: "zpg",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-isb"],
			["w-ar"],
		],
	},
	// E8 INX imp
	{
		opcode: 232,
		mnemonic: "INX",
		mode: "imp",
		code: [["r-pc", "dummy", "x++"]],
	},
	// E9 SBC imm
	{
		opcode: 233,
		mnemonic: "SBC",
		mode: "imm",
		code: [["r-pc++", "ro-sbc"]],
	},
	// EA NOP imp
	{
		opcode: 234,
		mnemonic: "NOP",
		mode: "imp",
		code: [["r-pc", "dummy"]],
	},
	// EB SBC imm
	{
		opcode: 235,
		mnemonic: "SBC",
		mode: "imm",
		undocumented: true,
		code: [["r-pc++", "ro-sbc"]],
	},
	// EC CPX abs
	{
		opcode: 236,
		mnemonic: "CPX",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar", "ro-cpx"],
		],
	},
	// ED SBC abs
	{
		opcode: 237,
		mnemonic: "SBC",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar", "ro-sbc"],
		],
	},
	// EE INC abs
	{
		opcode: 238,
		mnemonic: "INC",
		mode: "abs",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-inc"],
			["w-ar"],
		],
	},
	// EF ISB abs
	{
		opcode: 239,
		mnemonic: "ISB",
		altMnemonics: ["INS", "ISC"],
		mode: "abs",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr"],
			["r-ar"],
			["w-ar", "dummy", "mo-isb"],
			["w-ar"],
		],
	},
	// F0 BEQ rel
	{
		opcode: 240,
		mnemonic: "BEQ",
		mode: "rel",
		code: [
			["r-pc++", "eq?"],
			["r-pc", "dummy", "pc+=dr?"],
			["r-pc", "dummy", "pch=fix"],
		],
	},
	// F1 SBC iny
	{
		opcode: 241,
		mnemonic: "SBC",
		mode: "iny",
		code: [
			["r-pc++", "ar=dr"],
			["r-dr++"],
			["r-dr", "ar+=y?"],
			["r-ar", "?", "ah++", "ro-sbc"],
			["r-ar", "ro-sbc"],
		],
	},
	// F2 CIM imp
	{
		opcode: 242,
		mnemonic: "CIM",
		altMnemonics: ["KIL", "JAM", "HLT"],
		mode: "imp",
		undocumented: true,
		code: [
			["r-pc", "ar=ffff"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=fffe"],
			["r-ar", "ar=ffff"],
			["r-ar", "cc--"],
		],
	},
	// F3 ISB iny
	{
		opcode: 243,
		mnemonic: "ISB",
		altMnemonics: ["INS", "ISC"],
		mode: "iny",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-dr++"],
			["r-dr", "ar+=y?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-isb"],
			["w-ar"],
		],
	},
	// F4 NOP zpx
	{
		opcode: 244,
		mnemonic: "NOP",
		altMnemonics: ["DOP", "SKB"],
		mode: "zpx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar", "nop"],
		],
	},
	// F5 SBC zpx
	{
		opcode: 245,
		mnemonic: "SBC",
		mode: "zpx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar", "ro-sbc"],
		],
	},
	// F6 INC zpx
	{
		opcode: 246,
		mnemonic: "INC",
		mode: "zpx",
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar"],
			["w-ar", "dummy", "mo-inc"],
			["w-ar"],
		],
	},
	// F7 ISB zpx
	{
		opcode: 247,
		mnemonic: "ISB",
		altMnemonics: ["INS", "ISC"],
		mode: "zpx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-ar", "ar+=x"],
			["r-ar"],
			["w-ar", "dummy", "mo-isb"],
			["w-ar"],
		],
	},
	// F8 SED imp
	{
		opcode: 248,
		mnemonic: "SED",
		mode: "imp",
		code: [["r-pc", "dummy", "df=1"]],
	},
	// F9 SBC aby
	{
		opcode: 249,
		mnemonic: "SBC",
		mode: "aby",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "?", "ah++", "ro-sbc"],
			["r-ar", "ro-sbc"],
		],
	},
	// FA NOP imp
	{
		opcode: 250,
		mnemonic: "NOP",
		mode: "imp",
		undocumented: true,
		code: [["r-pc", "dummy"]],
	},
	// FB ISB aby
	{
		opcode: 251,
		mnemonic: "ISB",
		altMnemonics: ["INS", "ISC"],
		mode: "aby",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=y?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-isb"],
			["w-ar"],
		],
	},
	// FC NOP abx
	{
		opcode: 252,
		mnemonic: "NOP",
		altMnemonics: ["TOP", "SKW"],
		mode: "abx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?", "ah++", "nop"],
			["r-ar", "nop"],
		],
	},
	// FD SBC abx
	{
		opcode: 253,
		mnemonic: "SBC",
		mode: "abx",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?", "ah++", "ro-sbc"],
			["r-ar", "ro-sbc"],
		],
	},
	// FE INC abx
	{
		opcode: 254,
		mnemonic: "INC",
		mode: "abx",
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-inc"],
			["w-ar"],
		],
	},
	// FF ISB abx
	{
		opcode: 255,
		mnemonic: "ISB",
		altMnemonics: ["INS", "ISC"],
		mode: "abx",
		undocumented: true,
		code: [
			["r-pc++", "ar=dr"],
			["r-pc++", "ah=dr", "ar+=x?"],
			["r-ar", "?ah++"],
			["r-ar"],
			["w-ar", "dummy", "mo-isb"],
			["w-ar"],
		],
	},
];
