// Test double for `virtual:firmware-library`. The real module is generated by
// the firmware-library Vite plugin, which isn't loaded under vitest; this is
// aliased in via vitest.config.ts so the image library can be unit-tested.
// One representative built-in (a standard-8K BASIC cart) exercises the merge.

export const builtinFirmware = [
	{
		id: "firmware/fake-basic.rom",
		name: "Fake BASIC",
		url: "/fake-basic.rom",
		origin: "committed",
		size: 8192,
		format: "raw-cart-8k-a000-bfff",
		firmwareKey: "fake-basic",
		firmwareType: "basic",
		hash: "00".repeat(32),
		kind: { type: "cart", cartType: 1 },
	},
];
