// Assemble the XEX boot loader in `atari-src/` with spasm into the generated
// (and committed) `src/xex-loader-bytes.ts`. Runs as part of `pnpm build`;
// spasm must be built first — the root build orders that via the workspace
// dependency.
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { assemble, type Host } from "@sfotty-pie/spasm";
import prettier from "prettier";

// Node-like resolution: ids are absolute paths; relative specifiers resolve
// against the importing file's directory.
const host: Host = {
	resolve: (specifier, fromId) => resolve(dirname(fromId), specifier),
	read: (id) => readFile(id, "utf8"),
};

const entry = resolve(import.meta.dirname, "../atari-src/xex-loader.s");
const result = await assemble(entry, host);

for (const diagnostic of result.diagnostics) {
	process.stderr.write(
		`xex-loader.s: ${diagnostic.type}: ${diagnostic.message}\n`,
	);
}
if (result.diagnostics.some((d) => d.type === "error")) {
	process.exit(1);
}

if (result.output.length > 384) {
	process.stderr.write(
		`xex-loader.s: must fit 3 boot sectors (384 bytes), ` +
			`got ${result.output.length}\n`,
	);
	process.exit(1);
}

// Pad to the full three sectors.
const image = new Uint8Array(384);
image.set(result.output);

const bytes = [...image]
	.map((byte) => `0x${byte.toString(16).padStart(2, "0")}`)
	.join(", ");

const output = `// Generated by build-loader.ts from atari-src/xex-loader.s — do not edit.

/** The assembled XEX boot loader: three single-density boot sectors. */
export const XEX_LOADER = Uint8Array.from([${bytes}]);
`;

const outPath = join(import.meta.dirname, "xex-loader-bytes.ts");
const config = await prettier.resolveConfig(outPath);
await writeFile(
	outPath,
	await prettier.format(output, { ...config, parser: "typescript" }),
);
process.stdout.write(
	`Wrote src/xex-loader-bytes.ts (${result.output.length} bytes).\n`,
);
