// Assemble the boot loaders in `atari-src/` with spasm into the generated
// (and committed) `src/*-loader-bytes.ts` modules. Runs as part of
// `pnpm build`; spasm must be built first - the root build orders that via
// the workspace dependency.
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { assemble, type Host } from "@sfotty-pie/spasm";
import prettier from "prettier";

// Node-like resolution: ids are absolute paths; relative specifiers resolve
// against the importing file's directory.
const host: Host = {
	resolve: (specifier, fromId) => resolve(dirname(fromId), specifier),
	read: (id) => readFile(id, "utf8"),
};

const LOADERS = [
	{
		source: "xex-loader.s",
		out: "xex-loader-bytes.ts",
		constant: "XEX_LOADER",
		doc: "The assembled XEX boot loader: three single-density boot sectors.",
	},
	{
		source: "bas-loader.s",
		out: "bas-loader-bytes.ts",
		constant: "BAS_LOADER",
		doc: "The assembled BASIC boot loader: three single-density boot sectors.",
	},
];

for (const { source, out, constant, doc } of LOADERS) {
	const entry = resolve(import.meta.dirname, "../atari-src", source);
	const result = await assemble(entry, host);

	for (const diagnostic of result.diagnostics) {
		process.stderr.write(
			`${source}: ${diagnostic.type}: ${diagnostic.message}\n`,
		);
	}
	if (result.diagnostics.some((d) => d.type === "error")) {
		process.exit(1);
	}

	// The format derives the sector count and the loaders derive their buffer
	// and read position from it, but memory *placement* still assumes three
	// sectors (bas-loader's 512-byte top-of-RAM reservation, the buffers
	// sitting right past the image) - guard against silent growth.
	if (result.output.length !== 384) {
		process.stderr.write(
			`${source}: expected a 3-sector boot image (384 bytes), ` +
				`got ${result.output.length} - revisit the loaders' memory placement\n`,
		);
		process.exit(1);
	}

	const bytes = [...result.output]
		.map((byte) => `0x${byte.toString(16).padStart(2, "0")}`)
		.join(", ");

	const output = `// Generated by build-loader.ts from atari-src/${source} - do not edit.

/** ${doc} */
export const ${constant} = Uint8Array.from([${bytes}]);
`;

	const outPath = join(import.meta.dirname, out);
	const config = await prettier.resolveConfig(outPath);
	await writeFile(
		outPath,
		await prettier.format(output, { ...config, parser: "typescript" }),
	);
	process.stdout.write(`Wrote src/${out} (${result.output.length} bytes).\n`);
}
